### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by dude0001** [ThinkPad-Forum/TPFanControl#2]
If so, is there a well-maintained fork?

**Comment by Carghaez** [comment]
Hello Dude!

Actually there is two fork maintained, one by me (https://github.com/carghaez/TPFanControl) and one by @cjbdev (https://github.com/cjbdev/TPFanControl)

**Comment by pr0f35510n4l** [comment]
hey its not working on my lenovo laptop? how would i debug it
